const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const WineSchema = new Schema({
  name: { type: String, required: true },
  image: { type: String, required: true },
  category: { type: Schema.Types.ObjectId, ref: 'WineCategory', required: true },
  type: {
    type: String,
    enum: [
      'CABERNET SAUVIGNON',
      'MERLOT',
      'PINOT NOIR',
      'ZINFANDEL',
      'CHIANTI',
      'CHARDONNAY',
      'SAVIGNON BLANC',
      'PINOT GRIGIO',
      'REISLING',
      'ROSE',
      'CAMPAIGN',
      'PROSECCO',
      'MOSCATO',
      'ICEWINE',
      'PORT',
      'SHERRY',
      'MARSALA',
      'MALBEC',
      'MALVASIA',
      'MUSCAT',
      'MADEIRA',
      'ORANGE',
      'SRYAH',
      'RED BLEND',
      'WHITE BLEND',
      'GRENACHE BLANC',
    ],
    required: true,
  },
  description: { type: String, required: true },
  price: { type: mongoose.Types.Decimal128, required: true },
  bottleSizeInMl: { type: Number, required: true },
  ratings: [{ type: Number, required: true }],
});
